name: auto-push

on:
  push:
    branches:
      - master

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        path: source-repo
        persist-credentials: false
        fetch-depth: 0

    - name: Checkout destination repo
      uses: actions/checkout@v2
      with:
        path: destination-repo
        repository: pwanstax/monkey-d-frontend
        token: ${{ secrets.AUTO_PUSH_TOKEN }}
        fetch-depth: 0

    - name: Copy src folder and commit changes
      run: |
        cp -R source-repo/src destination-repo/
        cd destination-repo
        git config --global user.name "pwanstax"
        git config --global user.email "tutor_pawan@hotmail.com"
        git add src
        git commit -m "Merge src folder from source repository"
        git push origin main

