name: auto-push

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make changes
        run: |
          # Make changes to the cloned repository here

      - name: Push changes to other repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_PUSH_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'pwanstax'
          destination-repository: 'monkey-d-frontend'
          user-email: 'tutor_pawan@hotmail.com'

