name: Push to monkey-d-frontend

permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v1

    - name: Push to pwanstax/monkey-d-frontend
      env:
        API_KEY: ${{ secrets.AUTO_PUSH_TOKEN }}
      run: |
        git config --global user.name "pwanstax"
        git config --global user.email "tutor_pawan@hotmail.com"
        git remote add target_repo https://$API_KEY@github.com/pwanstax/monkey-d-frontend.git
        git checkout master
        git push target_repo master:main
